- README.md
To commit the information from this google doc https://docs.google.com/document/d/1PhHjcEn0zXbcYnnNz72N-EAmfOWurcF33Af6bBM68EI/edit?usp=sharing
> commit first readme

- mgs/README.md
Repo for managing projects related to LADOT
see #12
> mobility gap solutions

- data-events/README.md
Added new events to the list and changed some formatting.
> Events list

- airbnblistings/geofunctions/geofunctions.py
- airbnblistings/geofunctions/test_geofunctions.py
Adding the folder for airbnb listing and first function for helper functions that will be used for cleaning the data
> add new folder with new functions to help with clean up

- airbnblistings/geofunctions/geofunctions.py
- airbnblistings/geofunctions/test_geofunctions.py
Created bbox function to help create a boundary box for cleaning data. Added one test to  ensure any refactoring in the future still returns the correct  expected results.
> add bbox function

- LAANE/README.md
- LAANE/tests/test_tot_table.py
- LAANE/transformations/tot_table.py
WIP - started work on TOT table and tests I will finish in tomorrow and start on a new table.
> work on tot table

- LAANE/transformations/normalize_address.py
Docs improvement for normailze_address
> docs: re-wrote some of the normalize_address information

- LAANE/tests/test_assessor_table.py
- LAANE/transformations/assessor_table.py
Did some refactoring that addressed these issues:
- Rewrote the code to match the WeMake style guide.
- The functions are faster, and the memory is more efficient by ten times on average.
- The functions are pure now, with no added consequence to the DataFrames or Series passed into them.
All tests are still passing.
> refactor: update assessor table

- LAANE/README.md
- LAANE/tests/test_format_date.py
- LAANE/tests/test_normalize_address.py
- LAANE/transformations/assessor_table.py
- LAANE/transformations/format_date.py
I added new code  and tests for formatting date columns.
> feat: new code for date entries

- LAANE/README.md
- LAANE/tests/test_format_date.py
- LAANE/tests/test_normalize_address.py
- LAANE/transformations/assessor_table.py
- LAANE/transformations/format_date.py
updated some doc strings in files to better reflect the intent.
> docs: rewrote some docstrings etc

- LAANE/database/models.py
added airbnb tables and updated SQL Alchemy relationships.
> Feat: add Airbnb tables

- .gitignore
- LAANE/README.md
- LAANE/database/models.py
- LAANE/tests/test_hso_denials.py
- LAANE/transformations/format_date.py
- LAANE/transformations/hso_denials.py
Created a new file for hso_denial table, Added test for the custom functions. Added the code to insert the hso_denials data into the db.
1st dataset that's completely done
Need to go back to refactor the code because it's ugly
> feat: hso_denials insert function

- LAANE/database/models.py
- LAANE/tests/test_builds_table.py
- LAANE/tests/test_hso_denials.py
- LAANE/tests/test_normalize_address.py
- LAANE/transformations/hso_denials.py
- LAANE/transformations/insert_address.py
- LAANE/transformations/normalize_address.py
refactored some code and created a new abstraction function for inserting data.
> feat: add new abstraction function

- LAANE/database/models.py
- LAANE/transformations/hso_denials.py
- LAANE/transformations/tot.py
> feat: tot insert file

- LAANE/processingscripts/platform_ofs_alt.py
Script that enters one fine stay data into platform table but has a different column layout then the other one fine stay sheets.
> feat: new script

- LAANE/processingscripts/platform_ofs.py
- LAANE/processingscripts/platform_ofs_alt.py
- LAANE/transformations/process_multiple_files.py
Remove old code that does multiple files for a job and include a new module that handles that.
> refactor: add a new file to handle multiple files

- LAANE/processingscripts/hso_registrants.py
HSO_Registrant script is complete.
> feat: hso_registrant script

- LAANE/database/database.py
- LAANE/database/models.py
- LAANE/processingscripts/tot.py
Refactored tot script to make sure it is uploading to sqlite correctly.
> refactor/debug: debugging each script

- LAANE/processingscripts/complaints.py
- LAANE/processingscripts/tot.py
fixed complaints data to not have nulls and to not allow any state that don't use two letter abbreviation.
> bug fix: fixed bug for complaints data

- LAANE/processingscripts/categorically_inelligible.py
- LAANE/processingscripts/complaints.py
- LAANE/processingscripts/noncompliant.py
fixed categoically ineligible bug
> fixbug: fixed bug in categorically inelligible

- LAANE/processingscripts/exempt.py
fixed exempt table to match the rest of the database
> bugfix: fixed exempt script

- LAANE/database/database.py
- LAANE/processingscripts/hso_denials.py
- LAANE/processingscripts/hso_revocation.py
hsodenials bugs are remved, hsodenials script is good to go.
> fixbug in hsodenials

- LAANE/processingscripts/platform_ofs_alt.py
debug one fine stay scripts for address2 errors
> debug one fine stay scripts

- LAANE/database/models.py
- LAANE/processingscripts/airbnb_listings.py
- LAANE/processingscripts/platform_luxly.py
- LAANE/processingscripts/platform_ofs.py
airbnb script that uploads listings and host information
> feat: airbnb dataset script

- LAANE/database/database.py
- LAANE/processingscripts/airbnb_listings.py
- LAANE/processingscripts/airbnb_reviews.py
script for airbnb reviews is complete.
> feat: new processesing script

- LAANE/processingscripts/warnings.py
First commit fixes the warning script file.
The second commit adds an extra line describe what the script is for.
> Two commits

- LAANE/database/database.py
- LAANE/processingscripts/warnings_alt.py
This script is for warning files that don't have only addresses and dates.
> feat: new script for warning

- LAANE/database/database.py
- LAANE/processingscripts/citations.py
- LAANE/processingscripts/hso_denials.py
- LAANE/processingscripts/hso_registrants.py
- LAANE/processingscripts/hso_revocation.py
- LAANE/processingscripts/platform_luxly.py
- LAANE/processingscripts/platform_ofs.py
- LAANE/processingscripts/platform_ofs_alt.py
- LAANE/processingscripts/warnings.py
- LAANE/processingscripts/warnings_alt.py
added some code that debugs the ofs and luxly datasets.
Added a new script that handles warnings and citations.
> New scripts + debug

- LAANE/processingscripts/categorically_inelligible.py
debug categorically inelligibl data
> debug categorically inelligible

- LAANE/database/models.py
- LAANE/processingscripts/assessor.py
Last script, passes tests refactored a bit
> feat: assessor script
